---
name: Run tests & coverage

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch: {}

jobs:
  core:
    name: Tests & Coverage
    runs-on: ubuntu-latest
    container:
      image: caddy:builder
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run tests
      run: go test -v -coverprofile=./profile.cov ./...
    - name: Send coverage
      continue-on-error: true
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
